name: 'Bug report'
description: Report an issue with vuetify-use-dialog
labels: ['type: bug']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      id: bug-description
      attributes:
          label: Describe the bug
          description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us how in the description. Thanks!
          placeholder: Bug description
      validations:
          required: true
    - type: textarea
      id: reproduction
      attributes:
          label: Reproduction
          description: |
            Provide a minimal reproduction of the problem. Include a StackBlitz or link to a GitHub repository that we can easily run to recreate the issue. If a report is vague and does not have a reproduction, it will be closed without warning. 

            To get started, you can use the following StackBlitz template:
            https://stackblitz.com/edit/vitejs-vite-yktyla
      validations:
          required: true
    - type: dropdown
      id: severity
      attributes:
          label: Severity
          description: Select the severity of this issue
          options:
              - annoyance
              - blocking an upgrade
              - blocking all usage of vuetify-use-dialog
      validations:
          required: true
